### ISSUE TITLE
Remove watermark from the extension

### ISSUE THREAD

**Issue by kavitav25** [NielsLindberg/Qliksense.Extension.amWaterfall#21]
Hi, 
There's a watermark in the extension as "JS chart by amCharts".

Can you please help me to remove it?

**Comment by kavitav25** [comment]
Hello,

I cant find that option in amcharts.js file.

Please can you help me with the exact way.

Regards,
Kavita

**Comment by sattishbi** [comment]
......Documents\Qlik\Sense\Extensions\Qliksense.Extension.amWaterfall-master\Qliksense.Extension.amWaterfall-master\amCombo\library

Under library you can find amchart JScript file and clik on edit .
then
Search by JS
We will find out water mark name under the double codes and then remove it.

Hope this helps!!!

**Comment by kavitav25** [comment]
Ohh Yeah..Thank you so much...

**Comment by sattishbi** [comment]
Also can you look and suggest on my issue(#23) if you have any idea ...

I did some changes but still not able to add more than 6 measures.

I would like to add 7th measure as per end user requirement .

have you faced this issue ever before.??

Thanking you
Satish .......

**Comment by loveisfail** [comment]
I have deleted entire file under \\..\loveisfail$\My Documents\Qlik\Sense\Extensions\Qliksense.Extension.amWaterfall-master\amCombo\library

I deleted amcharts.js but still somewhere it is there only. Is there anything else do i need to delete?

**Comment by NielsLindberg** [comment]
Did you run replace All files in the lib folder and then ran the grunt
build?


tor. 31. maj 2018 9.09 AM skrev Anil Babu Samineni <notifications@github.com

**Comment by loveisfail** [comment]
Hearing - Terminology different, May be i don't the mean of yours?
