### ISSUE TITLE
Fill colors on the measures via expression do not work

### ISSUE THREAD

**Issue by gordanalozo** [NielsLindberg/Qliksense.Extension.amWaterfall#4]
I imported the latest updates but line & fill colors on the measures via expressions do not work for me. I have a simple expression: If(Order>=’3’, rgb(192,80,77), rgb(0,174,78)) and it does not work. All bars are colored in rgb(192,80,77). Could you please help? Thanks!

**Comment by NielsLindberg** [comment]
Can you try If(Order>=’3’, 'rgb(192,80,77)', 'rgb(0,174,78)')

It's parsing in the text hex/rgb representation to amcharts. If you dont do the quotes the qlikengine will evaluate it to something amchart doesnt recognize.

**Comment by gordanalozo** [comment]
I have tried that, but it does not work, colors are totally black now, it seems that Qlik does not read the colors when they are in quotes. Our Qlik version is 2.2.4, is that the problem this expression does not work as expected? Thanks!

**Comment by NielsLindberg** [comment]
I'll try and do a more indepth review on my end hopefully sometime during next week, have some exam stuff to do the next days.

Br. Niels

**Comment by gordanalozo** [comment]
Hi, hope your exams are going well. We upgraded to Qlik Sense 3.1 but the issue with colors stays the same, the line & fill colors on the measures via expressions do not work for us. Could not find the way to fix that in code... Thanks!

**Comment by NielsLindberg** [comment]
Hi gordana, 

Sorry for my slow reply, I'm having a hard time replicating your issue. When i do it on my end it seems to work fine.

![image](https://cloud.githubusercontent.com/assets/16624342/21004893/f0549d86-bd32-11e6-99d5-6e8f69290b54.png)

**Comment by gordanalozo** [comment]
Hi Niels,

Maybe I did not understand well what actually can be done when it comes to colors of the bars. Please see the attached screenshot. I assumed that if as you see on my screenshot the order is higher than 3 then my colors would be green otherwise it would be red.

Is it possible to achieve with the expression for the "Fill Color".

Thanks!


![image](https://cloud.githubusercontent.com/assets/16855056/21024651/550d44b0-bd53-11e6-9e32-232d42e52836.png)

**Comment by NielsLindberg** [comment]
Hi Gordana,

So you want it to return true for all dimension=Order with value >= 3 to one color and lesser to another.

If the order values are numeric you should be able to do if(Order>=3,'rgb(192,80,770)','rgb(0,174,78)')

Like i did here for this grawth with a 'numerical' dimension = [Car sales]
![image](https://cloud.githubusercontent.com/assets/16624342/21026867/cf246324-bd8e-11e6-8f75-bb60772e7197.png)

If its not numeric I dont think the >= operation works.

You could do something like this instead for coloring multiple non numerical dimensional values:
pick(match(Country, 'Japan', 'China')+1,'rgb(222,245,123)', 'rgb(123,123,123)', 'rgb(001,55,22)')

![image](https://cloud.githubusercontent.com/assets/16624342/21027208/1678e3fc-bd90-11e6-9d27-352085cbcaad.png)

**Comment by gordanalozo** [comment]
Hi Niels,

It worked with the formula for non numerical values:

pick(match([Survey Results],'Extremely Satisfied','Satisfied','Neither Satisfied or Dissatisfied','Dissatisfied', 'Extremely Dissatisfied'), 'rgb(0,174,78)', 'rgb(0,174,78)', 'rgb(0,174,78)', 'rgb(192,80,77)', 'rgb(192,80,77)')

Thank you so much!  I appreciate your help!! :)
